### ISSUE TITLE
Problem with SS5 / php8.1: [Deprecated] explode(): Passing null to parameter #2 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by RoyalPulp** [xini/silverstripe-cookie-consent#11]
Hey there!

I just loaded this module to a fresh SilverStripe 5 installation with PHP 8.1
While dev/build-ing the site, I get this Error :

[Deprecated] explode(): Passing null to parameter #2 ($string) of type string is deprecated
Line 157 in (...)vendor/innoweb/silverstripe-cookie-consent/src/CookieConsent.php

```
155     public static function getConsent()
156     {
157         return explode(',', Cookie::get(self::config()->get('cookie_name')));
158     }
```
should be easy to fix by guaranteeing, that instead of NULL there's an empty string at least ""

thanks for looking into it
Hendrik

**Comment by xini** [comment]
Sorry for that, fixed in 3.2.4.
